### ISSUE TITLE
Suggestion: include advertisement type in callback

### ISSUE THREAD

**Issue by ryan4volts** [colin-guyon/py-bluetooth-utils#1]
Basing my app around yours atm. Champion!

Please verify if I am correct below. I have been looking at my ble packet sniffer and noticed that this byte matches very well with `ADV_IND = 0x00` and `ADV_NONCONN_IND = 0x03` on local packets I've been inspecting. Is this true for you too?

In "bluetooth_utils.py -> parse_le_advertising_events" straight after your line `pkt = pkt[4:]` I would recommend adding something line `adv_type = pkt[1:2]` can be exposed through the callback function. This flag identifies how manufuacturer specific data should be interpreted as. Whether it has additional flags exists that changes "manufacturer specific data" to "service data".

**Comment by colin-guyon** [comment]
Hi, thank you !
What you observe is also true in my case (for example I get 0x03 for an ibeacon)
Would the changes made here suit your needs: #2 ? (adv_type exposed as an int)

**Comment by ryan4volts** [comment]
Yes it would!
After exposing it everything it working really well and those flags are accurate! Keep up the good work!

**Comment by colin-guyon** [comment]
Great, it is on master now,
thank you !
