### ISSUE TITLE
Can you add a license?

### ISSUE THREAD

**Issue by AlexDM0** [colin-guyon/py-bluetooth-utils#3]
Hi! We're working on a library for our smart home products which work with bluetooth (https://github.com/crownstone/bluenet-python-lib) and I'd like to use your utils in it.

I see a number of projects have just included your project, but it seems we can't legally use the code without a license (https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license).

For us MIT or Apache 2 would be great!

Cheers

**Comment by colin-guyon** [comment]
Ok, glad to hear you want to use this tool, and thank you for checking and pointing this lack of license!
I just added it on master ;)
Cheers
