### ISSUE TITLE
Wrong RSSI is displayed

### ISSUE THREAD

**Issue by JsBergbau** [colin-guyon/py-bluetooth-utils#5]
Using example BLE scanner RSSI is displayed wrong
most time it is just '0' but once you see '-85' which is a reasonable value.

![grafik](https://user-images.githubusercontent.com/37013344/98829848-f8bffe80-2439-11eb-8a7e-e0a356a9973f.png)

But I've also already seen '2' as value, which makes no sense to me

![grafik](https://user-images.githubusercontent.com/37013344/98829906-0b3a3800-243a-11eb-9c04-7f7ba990851b.png)

Of course device (Raspberry PI4) is working correctly and reporting reasonable RSSI data

![grafik](https://user-images.githubusercontent.com/37013344/98830341-94ea0580-243a-11eb-9231-748570ad110a.png)

**Comment by MS3FGX** [comment]
I'm seeing similar issues, though perhaps not quite as bad as this. Using both the example scanner and my own program I've written that makes use of the py-bluetooth-utils functions, I am occasionally seeing positive numbers for RSSI.

**Comment by colin-guyon** [comment]
Thank you for reporting this (and sorry for the delay), I will try to figure out what is occurring ;)

**Comment by JsBergbau** [comment]
Thanks for looking into this.
@MS3FGX Which device do you use?

**Comment by colin-guyon** [comment]
I just pushed a fix on master: afb68229e28db4d784a25078bc0afb6b41ca9783
In my case the values now are like the dbm values reported for eg. when running the btmon tool.
Please tell me if it is OK now ;)

**Comment by MS3FGX** [comment]
@colin-guyon Looks good to me with the new changes. Just logged a little over 100 packets from three different Xiaomi LYWSD03MMC sensors and all the RSSI values were in reasonable range.

**Comment by JsBergbau** [comment]
Thanks for the fix. Also works for me now.
