### ISSUE TITLE
Python 3.10 issue

### ISSUE THREAD

**Issue by satmandu** [colin-guyon/py-bluetooth-utils#9]
I'm getting this error when I use `bluetooth_utils.py`

```
    bluez.hci_send_cmd(sock, OGF_LE_CTL, OCF_LE_SET_SCAN_PARAMETERS, cmd_pkt)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by satmandu** [comment]
FIxed by https://github.com/pybluez/pybluez/pull/427

On ubuntu 22.04 I have a patch up at https://launchpad.net/~satadru-umich/+archive/ubuntu/updates

**Comment by colin-guyon** [comment]
Thank you to report that ;)
